program prjERP;

uses
  Vcl.Forms,
  UTelaInicial in 'UTelaInicial.pas' {FTelaInicial},
  uDmERP in 'uDmERP.pas' {DmERP: TDataModule},
  UBarraBotoes in 'Auxiliar\UBarraBotoes.pas' {FBarraBotoes: TFrame},
  uFuncoes in 'Auxiliar\uFuncoes.pas',
  uHashes in 'Auxiliar\uHashes.pas',
  ULogin in 'Auxiliar\ULogin.pas' {FLogin},
  UBarraBotoesItens in 'Auxiliar\UBarraBotoesItens.pas' {FBarraBotoesItens: TFrame},
  UFormCadastro in 'Auxiliar\UFormCadastro.pas' {FFormCadastro},
  UCobrancaCadastro in 'Financeiro\ContasReceber\UCobrancaCadastro.pas' {FCobrancaCadastro},
  UTrocarSenha in 'Administrativo\UTrocarSenha.pas' {FTrocarSenha},
  UAvisosSistema in 'Administrativo\UAvisosSistema.pas' {FAvisosSistema},
  uDmIntegracao in 'uDmIntegracao.pas' {DmIntegracao: TDataModule},
  USincronizarDados in 'Integracao\USincronizarDados.pas' {FSincronizarDados},
  UIntComRelatorios in 'Integracao\UIntComRelatorios.pas' {FIntComRelatorios},
  UIntSupItensConfPadrao in 'Integracao\UIntSupItensConfPadrao.pas' {FIntSupItensConfPadrao},
  UClienteCadastro in 'Gerais\Comercial\UClienteCadastro.pas' {FClienteCadastro},
  URepresentanteCadastro in 'Gerais\Comercial\URepresentanteCadastro.pas' {FRepresentanteCadastro},
  UEmpresaCadastro in 'Gerais\Gerencial\UEmpresaCadastro.pas' {FEmpresaCadastro},
  UFatDiarioCadastro in 'Faturamento\UFatDiarioCadastro.pas' {FFatDiarioCadastro},
  UVeiculoCadastro in 'Gerais\Gerencial\UVeiculoCadastro.pas' {FVeiculoCadastro},
  USetorCadastro in 'Gerais\Gerencial\USetorCadastro.pas' {FSetorCadastro},
  UUsuarioCadastro in 'Administrativo\UUsuarioCadastro.pas' {FUsuarioCadastro},
  UTelaCadastro in 'Administrativo\UTelaCadastro.pas' {FTelaCadastro},
  UTipoPatrimonioCadastro in 'Gerais\Controladoria\Patrimonio\UTipoPatrimonioCadastro.pas' {FTipoPatrimonioCadastro},
  UPatrimonioCadastro in 'Gerais\Controladoria\Patrimonio\UPatrimonioCadastro.pas' {FPatrimonioCadastro},
  UPatrimonioManutencaoCadastro in 'Controladoria\Patrimonio\UPatrimonioManutencaoCadastro.pas' {FPatrimonioManutencaoCadastro},
  UPatrimonioManutencaoConsulta in 'Controladoria\Patrimonio\UPatrimonioManutencaoConsulta.pas' {FPatrimonioManutencaoConsulta},
  UFornecedorTipoCadastro in 'Gerais\Gerencial\UFornecedorTipoCadastro.pas' {FFornecedorTipoCadastro},
  UFornecedorCadastro in 'Gerais\Comercial\UFornecedorCadastro.pas' {FFornecedorCadastro},
  UMotoristaCadastro in 'Gerais\Gerencial\UMotoristaCadastro.pas' {FMotoristaCadastro},
  UDocumentoTipoCadastro in 'Gerais\Controladoria\Contabilidade\UDocumentoTipoCadastro.pas' {FDocumentoTipoCadastro},
  UDespesaTipoCadastro in 'Gerais\Controladoria\Contabilidade\UDespesaTipoCadastro.pas' {FDespesaTipoCadastro},
  UBorderoCadastro in 'Controladoria\Contabilidade\UBorderoCadastro.pas' {FBorderoCadastro},
  UDocumentoCadastro in 'Controladoria\Contabilidade\UDocumentoCadastro.pas' {FDocumentoCadastro},
  URelatoriosContabilidade in 'Controladoria\Contabilidade\URelatoriosContabilidade.pas' {FRelatoriosContabilidade},
  UIntComPedidosAntigos in 'Integracao\UIntComPedidosAntigos.pas' {FIntComPedidosAntigos},
  URelatoriosContasReceber in 'Financeiro\ContasReceber\URelatoriosContasReceber.pas' {FRelatoriosContasReceber},
  UIntComControleImpressao in 'Integracao\UIntComControleImpressao.pas' {FIntComControleImpressao},
  UIntIndBaixaProducao in 'Integracao\UIntIndBaixaProducao.pas' {FIntIndBaixaProducao},
  UMensagemAviso in 'Auxiliar\UMensagemAviso.pas' {FMensagemAviso},
  UClassificacaoFiscalCadastro in 'Gerais\Controladoria\Contabilidade\UClassificacaoFiscalCadastro.pas' {FClassificacaoFiscalCadastro},
  UItemCadastro in 'Gerais\Suprimentos\UItemCadastro.pas' {FItemCadastro},
  UUnidadeMedidaCadastro in 'Gerais\Suprimentos\UUnidadeMedidaCadastro.pas' {FUnidadeMedidaCadastro},
  UItemGrupoCadastro in 'Gerais\Suprimentos\UItemGrupoCadastro.pas' {FItemGrupoCadastro},
  UItemFamiliaCadastro in 'Gerais\Suprimentos\UItemFamiliaCadastro.pas' {FItemFamiliaCadastro},
  UItemSubGrupoCadastro in 'Gerais\Suprimentos\UItemSubGrupoCadastro.pas' {FItemSubGrupoCadastro},
  UVariavelCadastro in 'Suprimentos\ConfiguradorItens\UVariavelCadastro.pas' {FVariavelCadastro},
  UItemVariavelVinculo in 'Suprimentos\ConfiguradorItens\UItemVariavelVinculo.pas' {FItemVariavelVinculo},
  UCampoCodigoGrid in 'Auxiliar\UCampoCodigoGrid.pas' {FCampoCodigoGrid},
  UItemVariavelItensBloq in 'Suprimentos\ConfiguradorItens\UItemVariavelItensBloq.pas' {FItemVariavelItensBloq},
  UColaboradorCadastro in 'Gerais\DeptoPessoal\UColaboradorCadastro.pas' {FColaboradorCadastro},
  UCargoCadastro in 'Gerais\DeptoPessoal\UCargoCadastro.pas' {FCargoCadastro},
  URegistroPonto in 'Administrativo\URegistroPonto.pas' {FRegistroPonto},
  UAlteracaoRegistroPonto in 'DeptoPessoal\UAlteracaoRegistroPonto.pas' {FAlteracaoRegistroPonto},
  URelatoriosDeptoPessoal in 'DeptoPessoal\URelatoriosDeptoPessoal.pas' {FRelatoriosDeptoPessoal},
  UIntIndItemRelacionadoCadastro in 'Integracao\UIntIndItemRelacionadoCadastro.pas' {FIntIndItemRelacionadoCadastro},
  UIntIndMaterialEntCadastro in 'Integracao\UIntIndMaterialEntCadastro.pas' {FIntIndMaterialEntCadastro},
  UIntIndMaterialSolicCadastro in 'Integracao\UIntIndMaterialSolicCadastro.pas' {FIntIndMaterialSolicCadastro},
  UIntIndMaterialEstoqueConsulta in 'Integracao\UIntIndMaterialEstoqueConsulta.pas' {FIntIndMaterialEstoqueConsulta},
  UMaterialMovimentoConsulta in 'Integracao\UMaterialMovimentoConsulta.pas' {FMaterialMovimentoConsulta},
  UIntFinRelatoriosFinanceiro in 'Integracao\UIntFinRelatoriosFinanceiro.pas' {FIntFinRelatoriosFinanceiro},
  UIntIndRelatoriosIndustrial in 'Integracao\UIntIndRelatoriosIndustrial.pas' {FIntIndRelatoriosIndustrial},
  UTransportadoraCadastro in 'Gerais\Comercial\UTransportadoraCadastro.pas' {FTransportadoraCadastro},
  UBancoCadastro in 'Gerais\Financeiro\UBancoCadastro.pas' {FBancoCadastro},
  UAgenciaCadastro in 'Gerais\Financeiro\UAgenciaCadastro.pas' {FAgenciaCadastro},
  UContaCadastro in 'Gerais\Financeiro\UContaCadastro.pas' {FContaCadastro},
  UCobrancaTipoCadastro in 'Gerais\Financeiro\UCobrancaTipoCadastro.pas' {FCobrancaTipoCadastro},
  UEscalaCadastro in 'Gerais\DeptoPessoal\UEscalaCadastro.pas' {FEscalaCadastro},
  UIntComCargaCadastro in 'Integracao\UIntComCargaCadastro.pas' {FIntComCargaCadastro},
  UIntComCargaEmAberto in 'Integracao\UIntComCargaEmAberto.pas' {FIntComCargaEmAberto},
  UReciboAvulsoCadastro in 'Financeiro\ContasPagar\UReciboAvulsoCadastro.pas' {FReciboAvulsoCadastro},
  UNaturezaCadastro in 'Gerais\Faturamento\UNaturezaCadastro.pas' {FNaturezaCadastro},
  UCentroCustoCadastro in 'Gerais\Gerencial\UCentroCustoCadastro.pas' {FCentroCustoCadastro},
  uSock in 'Auxiliar\uSock.pas',
  UPedidoCadastro in 'Comercial\UPedidoCadastro.pas' {FPedidoCadastro},
  UIntComAjustaCarga in 'Integracao\UIntComAjustaCarga.pas' {FIntComAjustaCarga},
  UIntComAnaliseVendas in 'Integracao\UIntComAnaliseVendas.pas' {FIntComAnaliseVendas},
  UIntComAtualizacaoTabPreco in 'Integracao\UIntComAtualizacaoTabPreco.pas' {FIntComAtualizacaoTabPreco},
  UIntComCotaFinanceira in 'Integracao\UIntComCotaFinanceira.pas' {FIntComCotaFinanceira},
  UMostrarImg in 'Auxiliar\UMostrarImg.pas' {FMostrarImg},
  UEmail in 'Auxiliar\UEmail.pas' {FEmail},
  UFrameAguarde in 'Auxiliar\UFrameAguarde.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'ERP';
  Application.CreateForm(TFTelaInicial, FTelaInicial);
  Application.CreateForm(TDmERP, DmERP);
  Application.CreateForm(TDmIntegracao, DmIntegracao);
  Application.Run;
end.
